version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-redes
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Pepper_926
      MYSQL_DATABASE: Proyecto_Redes
      MYSQL_USER: Gabriel
      MYSQL_PASSWORD: Pepper_926
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init-sql:/docker-entrypoint-initdb.d

  flask-app:
    build:
      context: ./servidor_http
    container_name: flask-redes
    ports:
      - "40000:5000"  # Puerto externo 40000 → Puerto Flask interno 5000
    depends_on:
      - mysql-db
    environment:
      - DB_HOST=mysql-db
      - DB_NAME=Proyecto_Redes
      - DB_USER=Gabriel
      - DB_PASS=Pepper_926

  ntp-syslog-server:
    build:
      context: ./servidor_syslog_ntp
    container_name: ntp_syslog_server
    ports:
      - "8514:8514/udp"
      - "8123:8123/udp"
    environment:
      - DB_HOST=mysql-db
      - DB_NAME=Proyecto_Redes
      - DB_USER=Gabriel
      - DB_PASS=Pepper_926
    depends_on:
      - mysql-db
    restart: always

volumes:
  db_data:
